server:
  port: 8888

spring:
  profiles:
    active: native

eureka:
  client:
    # https://github.com/spring-cloud/spring-cloud-netflix/issues/2541
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE}

logging:
  level:
    by:
      dzinevich:
        gateway: DEBUG
