server:
  port: 8082

spring:
  application:
    name: service-producer
  profiles:
    active: local

petservice:
  kafka:
    topic: pets
  threads:
    size: 2

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE}

logging:
  level:
    service-producer: DEBUG
