spring:
  datasource:
    url: jdbc:mysql://db:3306/service-producer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: service-comsumer
    password: password@321
  jpa:
    database: redis
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#disable service discovery
  cloud:
    discovery:
      enabled: false

# Enable logging for config troubleshooting
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE