spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_PASSWORD:rootpassword@321}
    initialize: true
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
# Enable logging for config troubleshooting
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE